version: '3'

services:
  jenkins:
    image: at/jenkins
    deploy:
     replicas: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Duser.timezone=Asia/Ho_Chi_Minh"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/asiantech/portainer/jenkins_home:/var/jenkins_home
    networks:
     - jenkins_net
     - public_net

networks:
  jenkins_net:
    driver: overlay
  public_net:
    external:
      name: public_net
